### ISSUE TITLE
Getting error main.lua or pdex.bin required after update to playdateSDK 1.13.5

### ISSUE THREAD

**Issue by Mahekaru** [midouest/vscode-playdate-debug#28]
Everything was working great and now after the update it's unusable :(.

**Comment by midouest** [comment]
What operating system platform/version are you using?

Everything is working fine for me on macOS 13.3.1.

**Comment by Mahekaru** [comment]
I'm running windows 11
No matter what I do I'm getting
![image](https://user-images.githubusercontent.com/2299058/233717545-27aa1a8a-689a-49e1-a49f-f7e6f6a55f00.png)

I have main.pdx
![image](https://user-images.githubusercontent.com/2299058/233717867-91393caa-d51d-4167-a3c0-6adbbaa26a4d.png)

And main.lua
![image](https://user-images.githubusercontent.com/2299058/233718158-2f93127f-ae0e-40a0-afd9-a45751e64ae9.png)

**Comment by midouest** [comment]
Thanks! I’ll take a look at this tomorrow when I have access to a Windows computer. 

I see in your screenshots that you have a main.pdx folder inside your source folder. Does deleting source/main.pdx make any difference?

**Comment by Mahekaru** [comment]
I had that in there to test it to see what folder it wanted the pdx folder in. Anyway I did delete it, but it didn't matter.

**Comment by midouest** [comment]
I am able to reproduce this issue on Windows 11 with Playdate SDK 1.13.5. It looks like there were breaking changes to how `pdc` handles Windows paths in 1.13.5. I'm going to report this issue on the Playdate dev forum.

In the meantime, here are a couple workarounds you can try:

1. Downgrade to Playdate SDK 1.13.4
2. Build via the `pdc` task in `.vscode/tasks.json` instead of using the "Run/Debug file in Playdate Simulator" button. You can copy-paste [this configuration example](https://github.com/midouest/vscode-playdate-debug#tasks-and-debug-launcher).

**Comment by midouest** [comment]
@Mahekaru This is now fixed in the latest release!

**Comment by Mahekaru** [comment]
Wooot!!! It's working again ^.....^ Thanks a bunch @midouest. 150 gold stars.
